language: java

if: tag is blank

services:
  - 'docker'

before_install:
  - curl -s https://raw.githubusercontent.com/aem-design/aemdesign-docker/master/scripts/get_config.sh | bash /dev/stdin $(pwd)/Dockerfile
  - curl -s https://raw.githubusercontent.com/aem-design/aemdesign-docker/master/scripts/get_version.sh | bash /dev/stdin


#build and test
install:
  - docker build --pull -t $IMAGE:$IMAGE_VERSION .
  - curl -s https://raw.githubusercontent.com/aem-design/aemdesign-docker/master/scripts/container_verify.sh | bash /dev/stdin
  - travis_terminate 1
  - docker images

#test
script:
  - echo "LOGIN TO HUB.DOCKER"
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo "PUSH HUB.DOCKER"
  - docker push $IMAGE:$IMAGE_VERSION
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker tag $IMAGE:$IMAGE_VERSION $IMAGE:latest && docker push $IMAGE:latest; fi
  - echo "UPDATE README IN HUB.DOCKER"
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker run --rm -v $(pwd):/data/ aemdesign/dockerhub-description "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$IMAGE"; fi

## Get the project version
before_deploy:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then git tag $TRAVIS_TAG; fi

## Create release in GitHub
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
